Reversing a List using a for loop:

In [13]:
original_list = [1, 2, 3, 4, 5]
reversed_list = []
for item in original_list:
    reversed_list.insert(0, item)

print(reversed_list)

[5, 4, 3, 2, 1]


The for loop iterates through each item in the original_list.
Using the insert() method, it adds each item to the beginning of the reversed_list, effectively reversing the order.

Reversing a String using a for loop:

In [14]:
original_string = "Hello, World!"
reversed_string = ''
for char in original_string:
    reversed_string = char + reversed_string

print(reversed_string)

!dlroW ,olleH


The for loop iterates through each character in the original_string.
For each character, it prepends it to the reversed_string, effectively building the reversed string character by character.

List comprehension examples

In [15]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']
pairs = [(num, char) for num in list1 for char in list2]
print(pairs)

[(1, 'a'), (1, 'b'), (1, 'c'), (2, 'a'), (2, 'b'), (2, 'c'), (3, 'a'), (3, 'b'), (3, 'c')]


del statement in Python, is used to remove an item or a slice from a list, or to delete variables. For instance:


Deleting an item from a list:

In [16]:
my_list = [1, 2, 3, 4, 5]
del my_list[2]  # Removes the item at index 2 (value 3)
print(my_list)  # Output: [1, 2, 4, 5]

[1, 2, 4, 5]


Deleting a slice from a list:

In [17]:
my_list = [1, 2, 3, 4, 5]
del my_list[1:3]  # Removes items from index 1 to index 2 ([2, 3])
print(my_list)  # Output: [1, 4, 5]

[1, 4, 5]


Deleting variables:

In [18]:
my_var = 10
del my_var  # Deletes the variable my_var
# Trying to access my_var after deletion will raise an error

### Python Object Oriented Programming(OOP)

* It is a programming paradigm that organizes code into objects, which are instances of classes.
* It revolves around the concept of objects that encapsulate data (attributes) and behavior (methods) into a single unit.
* Python is an object-oriented language, and OOP is a fundamental concept in Python programming.
* self represents the instance of the class. By using the “self” we can access the attributes and methods of the class in python. It binds the attributes with the given arguments.

#### Class and Object

In [4]:
class Phone:
    def make_call(self):
        print("I am making a call")
    def play_game(self):
        print("I am playing a game")        

In [2]:
p1=Phone()

In [3]:
p1.make_call()

I am making a call


In [4]:
p1.play_game()

I am playing a game


#### Adding Parameters to the class

In [5]:
class Phone:
    def set_color(self,color):
        self.color=color
    def set_cost(self,cost):
        self.cost=cost
    def show_color(self):
        return self.color
    def show_cost(self):
        return self.cost
    def make_call(self):
        print("I am making a call")
    def play_game(self):
        print("I am playing a game")  

In [6]:
p2=Phone()

In [7]:
p2.set_color("red")

In [9]:
p2.set_cost(5000)

In [10]:
p2.show_color()

'red'

In [11]:
p2.show_cost()

5000

In [12]:
p2.make_call()

I am making a call


In [13]:
p2.play_game()

I am playing a game


#### Creating class with Constructor

* The __init__ method is the Python equivalent of the C++ constructor in an object-oriented approach. The __init__  function is called every time an object is created from a class. The __init__ method lets the class initialize the object’s attributes and serves no other purpose. It is only used within classes. 

In [14]:
class Student:
    def __init__(self, name, age, student_id):
        self.name = name
        self.age = age
        self.student_id = student_id

    def display_info(self):
        print("Name of the student is",self.name)
        print("Age of the student is",self.age)
        print("ID of the student is",self.student_id)

In [15]:
student_instance = Student("Alice", 20, "12345")

In [16]:
student_instance.display_info()

Name of the student is Alice
Age of the student is 20
ID of the student is 12345


### NUMPY

In [60]:
#NumPy is usually imported under the np alias.

In [ ]:
import numpy as np

#### Dimensions in Arrays

0-D Arrays or Scalars

These are the elements in an array. Each value in an array is a 0-D array.

In [67]:
arr = np.array(42)

print(arr)

42


1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.These are the most common and basic arrays.

In [65]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [68]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

#### Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [69]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


#### Initializing with 0

In [90]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Initializing with same number

In [91]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

#### Initializing within a range

In [95]:
n1=np.arange(50,100)
n1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [96]:
n1=np.arange(50,100,5)
n1

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

#### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


#### Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [75]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


#### Slicing arrays
* Slicing in python means taking elements from one given index to another given index.

* Syntax: [start:end].

* Syntax: [start:end:step].

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

In [97]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [98]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [99]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


#### Iterating Arrays

In [76]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [77]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


#### Joining NumPy Arrays

In [102]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))


array([[10, 20, 30],
       [40, 50, 60]])

In [103]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))


array([10, 20, 30, 40, 50, 60])

In [104]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [100]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### NumPy Intersection and Difference

In [106]:
arr1 = np.array([10, 20, 30, 40, 50, 60])

arr2 = np.array([40, 50, 60, 70, 80, 90])


In [108]:
np.intersect1d(arr1,arr2)

array([40, 50, 60])

In [109]:
np.setdiff1d(arr1,arr2)

array([10, 20, 30])

In [110]:
np.setdiff1d(arr2,arr1)

array([70, 80, 90])

#### Array Mathematics 

In [117]:
n1=np.array([10,20,30])
n1=n1+5
print(n1)

[15 25 35]


In [118]:
n1=np.array([10,20,30])
n1=n1*10
print(n1)

[100 200 300]


In [119]:
n1=np.array([10,20,30])
n1=n1-5
print(n1)

[ 5 15 25]


In [120]:
n1=np.array([10,20,30])
n1=n1/10
print(n1)

[1. 2. 3.]


#### Math Functions

In [121]:
n1=np.array([10,20,30,40,50,60])

np.mean(n1)

35.0

In [123]:
n1=np.array([11,44,5,96,67,85])

np.median(n1)

55.5

In [124]:
n1=np.array([1,5,3,100,4,48])

np.std(n1)

36.59424666377065

#### Splitting NumPy Arrays

In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [80]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


#### Searching Arrays

In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7], dtype=int64),)


#### Sorting Arrays

In [5]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [84]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


#### NumPy Filter Array

In [85]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### PANDAS

In [4]:
import pandas as pd

#### Pandas Series
It is a one-dimensional array holding data of any type.

In [10]:
a = [1, 7, 2]

s1 = pd.Series(a)

print(s1)
type(s1)

0    1
1    7
2    2
dtype: int64


pandas.core.series.Series

#### Index
If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.

In [9]:
print(s1[0])

1


In [14]:
print(s2['day1'])

420


### Create your own Index:

In [15]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


### Series Object from Dictionary

In [16]:
calories = {"day1": 420, "day2": 380, "day3": 390}

s2 = pd.Series(calories)

print(s2)

day1    420
day2    380
day3    390
dtype: int64


In [23]:
s2 = pd.Series({"day1": 420, "day2": 380, "day3": 390}, index=["day3","day2","day4","day1"])

print(s2)

day3    390.0
day2    380.0
day4      NaN
day1    420.0
dtype: float64


### Extracting Individual elements from a Series

In [24]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])

s1[5]

6

In [31]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])

s1[-2:]

8     9
9    10
dtype: int64

In [33]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])

s1[:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Basic Math Operation on Series

In [40]:
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])

s1*5

0     5
1    10
2    15
3    20
4    25
5    30
6    35
7    40
8    45
9    50
dtype: int64

In [29]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])

s2=pd.Series([10,20,30,40,50,60,70,80,90])

s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

## Pandas DataFrame

Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

#### Create an Empty DataFrame
A basic DataFrame, which can be created is an Empty Dataframe.

In [44]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


#### Create a DataFrame from Lists
The DataFrame can be created using a single list or a list of lists.

In [43]:
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [45]:
data = [['Alex',10,'10'],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age','Marks'])
print(df)


     Name  Age Marks
0    Alex   10    10
1     Bob   12  None
2  Clarke   13  None


#### Create a DataFrame from Dictionary

In [51]:
import pandas as pd

data = {
  'Calories': [420, 380, 390],
  'Duration': [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)


   Calories  Duration
0       420        50
1       380        40
2       390        45


**Note** − Observe, **NaN** (Not a Number) is appended in missing areas

In [48]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [49]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


### Dataframe In-Built Functions

#### Reading CSV files as DataFrames

In [58]:
import pandas as pd

data = pd.read_csv('Shark_Tank.csv')
data

episode_number  pitch_number           brand_name  \
0                 1             1  BluePine Industries   
1                 1             2        Booz scooters   
2                 1             3  Heart up my Sleeves   
3                 2             4           Tagz Foods   
4                 2             5       Head and Heart   
..              ...           ...                  ...   
112              34           113        Green Protein   
113              34           114              On2Cook   
114              35           115        Jain Shikanji   
115              35           116                Woloo   
116              35           117         Elcare India   

                                              idea  deal  pitcher_ask_amount  \
0                                     Frozen Momos     1                50.0   
1    Renting e-bike for mobility in private spaces     1                40.0   
2                               Detachable Sleeves     1                25.0   
3                             Healthy Potato Chips     1                70.0   
4                         Brain Development Course     0                50.0   
..                                             ...   ...                 ...   
112                            Plant-Based Protein     0                60.0   
113                         Fastest Cooking Device     0               100.0   
114                                       Lemonade     1                40.0   
115                                Washroom Finder     0                50.0   
116                           Carenting for Elders     0               100.0   

     ask_equity  ask_valuation  deal_amount  deal_equity  ...  ashneer_deal  \
0           5.0        1000.00         75.0        16.00  ...             1   
1          15.0         266.67         40.0        50.00  ...             1   
2          10.0         250.00         25.0        30.00  ...             0   
3           1.0        7000.00         70.0         2.75  ...             1   
4           5.0        1000.00          0.0         0.00  ...             0   
..          ...            ...          ...          ...  ...           ...   
112         2.0        3000.00          0.0         0.00  ...             0   
113         1.0       10000.00          0.0         0.00  ...             0   
114         8.0         500.00         40.0        30.00  ...             1   
115         4.0        1250.00          0.0         0.00  ...             0   
116         2.5        4000.00          0.0         0.00  ...             0   

     anupam_deal  aman_deal  namita_deal  vineeta_deal  peyush_deal  \
0              0          1            0             1            0   
1              0          0            0             1            0   
2              1          0            0             1            0   
3              0          0            0             0            0   
4              0          0            0             0            0   
..           ...        ...          ...           ...          ...   
112            0          0            0             0            0   
113            0          0            0             0            0   
114            1          1            0             1            0   
115            0          0            0             0            0   
116            0          0            0             0            0   

     ghazal_deal  total_sharks_invested  amount_per_shark  equity_per_shark  
0              0                      3              25.0          5.333333  
1              0                      2              20.0         25.000000  
2              0                      2              12.5         15.000000  
3              0                      1              70.0          2.750000  
4              0                      0               0.0          0.000000  
..           ...                    ...               ...               ...  

In [59]:
len(data)

117

In [60]:
data.shape

(117, 28)

In [62]:
data.head()

episode_number  pitch_number           brand_name  \
0               1             1  BluePine Industries   
1               1             2        Booz scooters   
2               1             3  Heart up my Sleeves   
3               2             4           Tagz Foods   
4               2             5       Head and Heart   

                                            idea  deal  pitcher_ask_amount  \
0                                   Frozen Momos     1                50.0   
1  Renting e-bike for mobility in private spaces     1                40.0   
2                             Detachable Sleeves     1                25.0   
3                           Healthy Potato Chips     1                70.0   
4                       Brain Development Course     0                50.0   

   ask_equity  ask_valuation  deal_amount  deal_equity  ...  ashneer_deal  \
0         5.0        1000.00         75.0        16.00  ...             1   
1        15.0         266.67         40.0        50.00  ...             1   
2        10.0         250.00         25.0        30.00  ...             0   
3         1.0        7000.00         70.0         2.75  ...             1   
4         5.0        1000.00          0.0         0.00  ...             0   

   anupam_deal  aman_deal  namita_deal  vineeta_deal  peyush_deal  \
0            0          1            0             1            0   
1            0          0            0             1            0   
2            1          0            0             1            0   
3            0          0            0             0            0   
4            0          0            0             0            0   

   ghazal_deal  total_sharks_invested  amount_per_shark  equity_per_shark  
0            0                      3              25.0          5.333333  
1            0                      2              20.0         25.000000  
2            0                      2              12.5         15.000000  
3            0                      1              70.0          2.750000  
4            0                      0               0.0          0.000000  

[5 rows x 28 columns]

In [63]:
data.tail()

episode_number  pitch_number     brand_name                    idea  \
112              34           113  Green Protein     Plant-Based Protein   
113              34           114        On2Cook  Fastest Cooking Device   
114              35           115  Jain Shikanji                Lemonade   
115              35           116          Woloo         Washroom Finder   
116              35           117   Elcare India    Carenting for Elders   

     deal  pitcher_ask_amount  ask_equity  ask_valuation  deal_amount  \
112     0                60.0         2.0         3000.0          0.0   
113     0               100.0         1.0        10000.0          0.0   
114     1                40.0         8.0          500.0         40.0   
115     0                50.0         4.0         1250.0          0.0   
116     0               100.0         2.5         4000.0          0.0   

     deal_equity  ...  ashneer_deal  anupam_deal  aman_deal  namita_deal  \
112          0.0  ...             0            0          0            0   
113          0.0  ...             0            0          0            0   
114         30.0  ...             1            1          1            0   
115          0.0  ...             0            0          0            0   
116          0.0  ...             0            0          0            0   

     vineeta_deal  peyush_deal  ghazal_deal  total_sharks_invested  \
112             0            0            0                      0   
113             0            0            0                      0   
114             1            0            0                      4   
115             0            0            0                      0   
116             0            0            0                      0   

     amount_per_shark  equity_per_shark  
112               0.0               0.0  
113               0.0               0.0  
114              10.0               7.5  
115               0.0               0.0  
116               0.0               0.0  

[5 rows x 28 columns]

In [64]:
data.describe()

episode_number  pitch_number        deal  pitcher_ask_amount  \
count      117.000000    117.000000  117.000000          117.000000   
mean        18.735043     59.000000    0.555556          319.854709   
std         10.070778     33.919021    0.499041         2767.842777   
min          1.000000      1.000000    0.000000            0.001010   
25%         10.000000     30.000000    0.000000           45.000000   
50%         19.000000     59.000000    1.000000           50.000000   
75%         27.000000     88.000000    1.000000           80.000000   
max         35.000000    117.000000    1.000000        30000.000000   

       ask_equity  ask_valuation  deal_amount  deal_equity  deal_valuation  \
count  117.000000     117.000000   117.000000   117.000000      117.000000   
mean     5.188034    3852.462479    31.982915     8.963504      467.104872   
std      3.892121   11931.601957    36.687391    13.106769      919.988864   
min      0.250000       0.010000     0.000000     0.000000        0.000000   
25%      2.500000     666.670000     0.000000     0.000000        0.000000   
50%      5.000000    1250.000000    25.000000     3.000000      100.000000   
75%      7.500000    2857.140000    50.000000    15.000000      500.000000   
max     25.000000  120000.000000   150.000000    75.000000     6666.670000   

       ashneer_present  ...  ashneer_deal  anupam_deal   aman_deal  \
count       117.000000  ...    117.000000   117.000000  117.000000   
mean          0.837607  ...      0.179487     0.205128    0.239316   
std           0.370397  ...      0.385410     0.405532    0.428501   
min           0.000000  ...      0.000000     0.000000    0.000000   
25%           1.000000  ...      0.000000     0.000000    0.000000   
50%           1.000000  ...      0.000000     0.000000    0.000000   
75%           1.000000  ...      0.000000     0.000000    0.000000   
max           1.000000  ...      1.000000     1.000000    1.000000   

       namita_deal  vineeta_deal  peyush_deal  ghazal_deal  \
count   117.000000    117.000000   117.000000   117.000000   
mean      0.188034      0.128205     0.230769     0.059829   
std       0.392420      0.335756     0.423137     0.238190   
min       0.000000      0.000000     0.000000     0.000000   
25%       0.000000      0.000000     0.000000     0.000000   
50%       0.000000      0.000000     0.000000     0.000000   
75%       0.000000      0.000000     0.000000     0.000000   
max       1.000000      1.000000     1.000000     1.000000   

       total_sharks_invested  amount_per_shark  equity_per_shark  
count             117.000000        117.000000        117.000000  
mean                1.230769         18.132481          5.583590  
std                 1.410457         23.588682         10.803799  
min                 0.000000          0.000000          0.000000  
25%                 0.000000          0.000000          0.000000  
50%                 1.000000         10.000000          1.250000  
75%                 2.000000         25.000000          6.000000  
max                 5.000000        100.000000         75.000000  

[8 rows x 26 columns]

In [65]:
data.dtypes

episode_number             int64
pitch_number               int64
brand_name                object
idea                      object
deal                       int64
pitcher_ask_amount       float64
ask_equity               float64
ask_valuation            float64
deal_amount              float64
deal_equity              float64
deal_valuation           float64
ashneer_present            int64
anupam_present             int64
aman_present               int64
namita_present             int64
vineeta_present            int64
peyush_present             int64
ghazal_present             int64
ashneer_deal               int64
anupam_deal                int64
aman_deal                  int64
namita_deal                int64
vineeta_deal               int64
peyush_deal                int64
ghazal_deal                int64
total_sharks_invested      int64
amount_per_shark         float64
equity_per_shark         float64
dtype: object

In [66]:
data.columns

Index(['episode_number', 'pitch_number', 'brand_name', 'idea', 'deal',
       'pitcher_ask_amount', 'ask_equity', 'ask_valuation', 'deal_amount',
       'deal_equity', 'deal_valuation', 'ashneer_present', 'anupam_present',
       'aman_present', 'namita_present', 'vineeta_present', 'peyush_present',
       'ghazal_present', 'ashneer_deal', 'anupam_deal', 'aman_deal',
       'namita_deal', 'vineeta_deal', 'peyush_deal', 'ghazal_deal',
       'total_sharks_invested', 'amount_per_shark', 'equity_per_shark'],
      dtype='object')

### loc VS iloc

#### loc in Pandas
loc is label-based, which means that we have to specify the name of the rows and columns that we need to filter out.

For example, let’s say we search for the rows whose index is 1, 2 or 100. We will not get the first, second or the hundredth row here. Instead, we will get the results only if the name of any index is 1, 2 or 100.

So, we can filter the data using the loc function in Pandas even if the indices are not an integer in our dataset.

#### iloc in Pandas
On the other hand, iloc is integer index-based. So here, we have to specify rows and columns by their integer index.

Let’s say we search for the rows with index 1, 2 or 100. It will return the first, second and hundredth row, regardless of the name or labels we have in the index in our dataset.

##### EXAMPLE 1

In [81]:
import pandas as pd

#create DataFrame
df = pd.DataFrame({'team': ['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'],
                   'points': [5, 7, 7, 9, 12, 9, 9, 4],
                   'assists': [11, 8, 10, 6, 6, 5, 9, 12]},
                   index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

#view DataFrame
df


team  points  assists
A    A       5       11
B    A       7        8
C    A       7       10
D    A       9        6
E    B      12        6
F    B       9        5
G    B       9        9
H    B       4       12

In [82]:
#select rows with index labels 'E' and 'F'
df.loc[['E', 'F']]

team  points  assists
E    B      12        6
F    B       9        5

In [83]:
#select 'E' and 'F' rows and 'team' and 'assists' columns
df.loc[['E', 'F'], ['team', 'assists']]

team  assists
E    B        6
F    B        5

In [84]:
#select rows in index positions 4 through 6 (not including 6)
df.iloc[4:6]

team  points  assists
E    B      12        6
F    B       9        5

In [85]:
#select rows in range 4 through 6 and columns in range 0 through 2
df.iloc[4:6, 0:2]

team  points
E    B      12
F    B       9

##### EXAMPLE 2

In [86]:
s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2]) 
print(s)

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object


In [87]:
 s.loc[0]    # value at index label 0

'd'

In [88]:
s.iloc[0]    # value at index location 0

'a'